### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by gohlex** [nitaybz/homebridge-delay-switch#1]
Hi There, thanks for the developing this plug in. I'm in a situation which i find this plug is may be useful but need a little help how to make use of this? I've manage to configured it and appear in home app (and eve also).

I'm trying to setup a scene where it will turn off 1 smart plug and 1 light, but i would like a delay in between. but when test the scene, both still turn off at the same time without any delay... any idea how i could get it work?

Thanks in advance.

**Comment by nitaybz** [comment]
@gohlex This plugin works that way:
once the switch is turned on, it will turn off automatically after the amount of time set in the config.
to make your automation work you need to use this switch with your first scene, make sure your Scene will turn on that switch (among with your smart plug for example).
other than that you need to set automation to trigger when this switch is turned off.
that automation will turn on your desired light after the delay switch is turned off (automatically).

let me know if everything is clear now.

**Comment by gohlex** [comment]
Thanks Pal, manage to get it work now. had to use Eve to add the trigger though. Native home have don't have option to set trigger i reckon...

**Comment by kalety** [comment]
Hello, I don´t get it work... I wish: movement sensor detects->switch on lights-> switch delay (several seconds)-> switch off lights... . I tried several ways but.... nothing... Can you help me with a clearer example?

Thanks in advance!!!
