### ISSUE TITLE
Hide delay switch in Homekit

### ISSUE THREAD

**Issue by mmarte85** [nitaybz/homebridge-delay-switch#10]
First of all, thank you very much for this excellent plugin. I use it for so many automations in my smart home. It is great!

I have one question: is it possible to hide a delay switch from homekit? I still want to be able to us it in my automations and scenes, but only want to hide it from my rooms (I don't want my other homekit users to toggle a switch by mistake). Thanks.

**Comment by nitaybz** [comment]
unfortunately it is not possible... it would be if the plugin was a sensor and not a switch...
try and look for a plugin called homebridge-timer...
