### ISSUE TITLE
Problem after trying to add 4th delay accessory

### ISSUE THREAD

**Issue by peros550** [nitaybz/homebridge-delay-switch#11]
When I tried to add the 4th delay accessory, the whole homebridge started act abnormally. More specifically, I started to see some homebridge (not all) accessories moved in different rooms and "in not responding" status. 

Everything came back to normal when I removed the 4th delay accessory.

**Comment by nitaybz** [comment]
try install the latest...

**Comment by peros550** [comment]
Hi, thanks for the update. I just installed the latest version but unfortunately problem remains.

**Comment by nitaybz** [comment]
please try again the latest

**Comment by peros550** [comment]
Hi initial testing shows positive results. I will keep testing and update you in a few days. 

Many thanks for your support.

**Comment by nitaybz** [comment]
please install the latest since the last one had an error in the code...

**Comment by peros550** [comment]
Installed the latest version, it seems to work nicely. Many Thanks!
If it's ok with you, leave the topic open for 5-10 days so that further testing can take place and then we can close it.
