### ISSUE TITLE
TypeError: Cannot read property 'bind' of undefined - after updating v0.0.5 to v2.0.0

### ISSUE THREAD

**Issue by DJay-X** [nitaybz/homebridge-delay-switch#14]
Jun 06 11:54:34 raspberrypi homebridge[7729]: [2018-6-6 11:54:34] [DelaySwitch 5 Min] Initializing DelaySwitch accessory...
Jun 06 11:54:34 raspberrypi homebridge[7729]: /usr/local/lib/node_modules/homebridge-delay-switch/index.js:36
Jun 06 11:54:34 raspberrypi homebridge[7729]: .on('get', this.getOn.bind(this))
Jun 06 11:54:34 raspberrypi homebridge[7729]: ^
Jun 06 11:54:34 raspberrypi homebridge[7729]: TypeError: Cannot read property 'bind' of undefined
Jun 06 11:54:34 raspberrypi homebridge[7729]: at delaySwitch.getServices (/usr/local/lib/node_modules/homebridge-delay-switch/index.js:36:31)
Jun 06 11:54:34 raspberrypi homebridge[7729]: at Server._createAccessory (/usr/local/lib/node_modules/homebridge/lib/server.js:408:36)
Jun 06 11:54:34 raspberrypi homebridge[7729]: at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:296:26)
Jun 06 11:54:34 raspberrypi homebridge[7729]: at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:86:38)
Jun 06 11:54:34 raspberrypi homebridge[7729]: at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
Jun 06 11:54:34 raspberrypi homebridge[7729]: at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
Jun 06 11:54:34 raspberrypi homebridge[7729]: at Module._compile (internal/modules/cjs/loader.js:654:30)
Jun 06 11:54:34 raspberrypi homebridge[7729]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
Jun 06 11:54:34 raspberrypi homebridge[7729]: at Module.load (internal/modules/cjs/loader.js:566:32)
Jun 06 11:54:34 raspberrypi homebridge[7729]: at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
Jun 06 11:54:34 raspberrypi homebridge[7729]: at Function.Module._load (internal/modules/cjs/loader.js:498:3)
Jun 06 11:54:34 raspberrypi homebridge[7729]: at Function.Module.runMain (internal/modules/cjs/loader.js:695:10)
Jun 06 11:54:34 raspberrypi homebridge[7729]: at startup (internal/bootstrap/node.js:201:19)
Jun 06 11:54:34 raspberrypi homebridge[7729]: at bootstrapNodeJSCore (internal/bootstrap/node.js:516:3)
Jun 06 11:54:34 raspberrypi systemd[1]: homebridge.service: main process exited, code=exited, status=1/FAILURE

**Comment by nitaybz** [comment]
Fixing now

**Comment by nitaybz** [comment]
try again now... 2.0.1

**Comment by DJay-X** [comment]
@nitaybz Thanks for your fast reply. With v2.0.1 Homebridge works again. 👍🏻
Thanks for you ongoing work on development and sharing with us.

**Comment by nitaybz** [comment]
please install the latest since the last one had an error in the code...
