### ISSUE TITLE
Question - Feature Request: Option to hide motion sensors from home app

### ISSUE THREAD

**Issue by peros550** [nitaybz/homebridge-delay-switch#15]
Hi, 

I have been using this plugin and seems very stable since your last update. I am using it to add multiple timers in the form of switches. 

Home app has the option to trigger automation actions when a switch change state. Hence, in my case I don't need the motion sensors.

Do you thing you can make a parameter (true/false) on json config file which will control wether motion sensor is shown in home app or not?

Thanks!

**Comment by paqpaqpaq** [comment]
I haven't got a clue really why this extra motion sensor would be useful to begin with...?
Simply trigger the automation when the delay switch ends. Why the extra fake sensor?

**Comment by nitaybz** [comment]
I'll make that request you asked to remove that sensor... But I'll explain why it's very useful:
up until today, when a switch went Off, the scene/automation would start and I didn't have a way to cancel the automation... for example:

I'm using it to delay the state change of my security system so I can get out of the house before the alarm goes off, but if I want to cancel the counter without setting the alarm or without triggering any action, that was impossible.

with the new sensor it's very easy to control that... My automations are based on the Switch "ON" state and sensor "Triggered" state so I can fully control it. I even have automation that stop the timer (turn off the switch) in certain occasions...

I hope it make things clear... but anyway I'm gonna add an option to add `"disableSensor": false` to config.

**Comment by nitaybz** [comment]
Done
2.1.0

**Comment by BindersFullOfWomen** [comment]
Your security system explanation makes perfect sense. I wasn't fully understanding the concept from the readme, but I get it now.

**Comment by paqpaqpaq** [comment]
great!  thanks :)

**Comment by peros550** [comment]
many thanks!
