### ISSUE TITLE
Motion sensors unreliable

### ISSUE THREAD

**Issue by iRonin** [nitaybz/homebridge-delay-switch#16]
I've been using the plugin for around a year with just switches and I can say the switches work very reliably. I've noticed the motion sensors a week or two ago and decided to give them a go and I can say they do not work reliably. I can help debug but I have no idea of what's going on. I have quite a lot of them - basically I've got 3 rooms with 5 switches/sensors in each. These are with windows and 5/10/15/30/60 minutes ventilation programs and sometimes the closing is not being triggered.

**Comment by iRonin** [comment]
I can add that there is `Triggering Motion Sensor` log entry - it seems some of the triggers are not pushed to / caught by HomeKit automation for some reason.

**Comment by nitaybz** [comment]
hey @iRonin !
thanks for your feedback....
looking at the very simple code, I don't think there is much I can do... it work very reliably to me.
do you have any other motion sensors in your home that work as you expect? I found that some times when the automations are not working as expected it can come form the hub (can even happen only with sensors and not with switches).

Did you encounter a situation where there wasn't even `Triggering Motion Sensor` log entry when there should have been? or do you think it's just about the connection with HomeKit itself?
