### ISSUE TITLE
How to use delay?

### ISSUE THREAD

**Issue by pipa2493** [nitaybz/homebridge-delay-switch#17]
Hi There, thanks for the developing this plug in. I've manage to configured it and appear in home app.

Сan't figure out how to link it to a light bulb or switch hdmi to TV? I have to merge this into config.json or can I still do it through the app?

**Comment by pipa2493** [comment]
Want to switch HDMI with delay, here is my config file.json
{
        "bridge": {
                "name": "Homebridge_KNX",
                "username": "CC:25:3D:E2:CE:30",
                "port": 51826,
                "pin": "031-45-155"
        },
        "description": "This is an example configuration file for KNX platform shim",
        "platforms": [
        ],
        "accessories": [
{
        "accessory": "SamsungTV",
        "name": "Домашний кинотеатр",
        "ip": "192.168.0.27",
        "mac": "40:16:3B:D9:DE:4A",
        "type": "power"
},
    {
        "accessory": "SamsungTV",
        "name": "CHDOWN",
        "ip": "192.168.0.27",
        "mac": "40:16:3B:D9:DE:4A",
        "type": "custom",
        "command": "KEY_CHDOWN"
    },
        {
        "accessory": "SamsungTV",
        "name": "HDMI CH",
        "ip": "192.168.0.27",
        "mac": "40:16:3B:D9:DE:4A",
        "type": "custom",
        "command": "KEY_HDMI",
        "repeat": 2,
        "delay": 500
    },
       {
         "accessory": "DelaySwitch",
         "name": "DelaySwitch",
         "disableSensor": false,
         "delay": 5000
       }
         ]
 }

**Comment by nitaybz** [comment]
linking between the delay switch to other accessory is only made from within the app.... home app or other 3rd party apps like EVE, you can see some automations for example in the main readme file

**Comment by pipa2493** [comment]
Thank you! I did it!
