### ISSUE TITLE
can't add homebridge to house when adding accessories

### ISSUE THREAD

**Issue by zork17** [nitaybz/homebridge-delay-switch#2]
when I add 5 accessories/DelaySwitch I can't add homebridge to the house on iOS.

**Comment by nitaybz** [comment]
please send your logs so I can better understand the problem...

**Comment by zork17** [comment]
There is no info in the logs. 
How can I produce a debug log?

**Comment by nitaybz** [comment]
you can check here:
https://github.com/nfarina/homebridge/issues/873
https://github.com/nfarina/homebridge/issues/881

it should be on your console though

if not you can also run homebridge this way:
DEBUG=* homebridge -D -P

which will print more details on your console.

also please explain more about your problems... what happen when you only add 4 accessories? and what do . you mean by 

> can't add homebridge to the house on iOS.

**Comment by zork17** [comment]
1) I deleted everything and started from scratch and finally had homebridge working with KNX and HTTP WEBHOOKS plugins.
2) Then I added only one delay switch accessory to config.json.
3) I restarted homebridge.
4) Now when I open the Home app in IOS I see that the home is empty. It asks me to add the first device.
5) The homebridge hub is in the main room but it is with red no response status.
6) There are no logs that are related to delay switch and no errors.

**Comment by zork17** [comment]
@nitaybz 
This is the log file:
[daemon.txt](https://github.com/nitaybz/homebridge-delay-switch/files/754538/daemon.txt)

**Comment by zork17** [comment]
Now I need to delete homebridge from the main room on IOS and delete the persist folder on raspberry pi..
And I still can't add homebridge as a device.

This is the log:
Feb  6 15:03:29 RSBPI homebridge[1503]: Mon, 06 Feb 2017 13:03:29 GMT EventedHTTPServer [::ffff:10.0.0.51] New connection from client
Feb  6 15:03:29 RSBPI homebridge[1503]: Mon, 06 Feb 2017 13:03:29 GMT EventedHTTPServer [::ffff:10.0.0.51] HTTP server listening on port 42391
Feb  6 15:03:29 RSBPI homebridge[1503]: Mon, 06 Feb 2017 13:03:29 GMT EventedHTTPServer [::ffff:10.0.0.51] HTTP request: /pair-setup
Feb  6 15:03:29 RSBPI homebridge[1503]: Mon, 06 Feb 2017 13:03:29 GMT HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pair-setup
Feb  6 15:03:29 RSBPI homebridge[1503]: Mon, 06 Feb 2017 13:03:29 GMT HAPServer [CC:22:3D:E3:CE:30] Pair step 1/5
Feb  6 15:03:30 RSBPI homebridge[1503]: Mon, 06 Feb 2017 13:03:30 GMT EventedHTTPServer [::ffff:10.0.0.51] HTTP Response is finished
Feb  6 15:03:39 RSBPI homebridge[1503]: Mon, 06 Feb 2017 13:03:39 GMT EventedHTTPServer [::ffff:10.0.0.51] HTTP request: /pair-setup
Feb  6 15:03:39 RSBPI homebridge[1503]: Mon, 06 Feb 2017 13:03:39 GMT HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pair-setup
Feb  6 15:03:39 RSBPI homebridge[1503]: Mon, 06 Feb 2017 13:03:39 GMT HAPServer [CC:22:3D:E3:CE:30] Pair step 2/5
Feb  6 15:03:40 RSBPI homebridge[1503]: Mon, 06 Feb 2017 13:03:40 GMT EventedHTTPServer [::ffff:10.0.0.51] HTTP Response is finished
Feb  6 15:03:40 RSBPI homebridge[1503]: Mon, 06 Feb 2017 13:03:40 GMT EventedHTTPServer [::ffff:10.0.0.51] HTTP request: /pair-setup
Feb  6 15:03:40 RSBPI homebridge[1503]: Mon, 06 Feb 2017 13:03:40 GMT HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pair-setup
Feb  6 15:03:40 RSBPI homebridge[1503]: Mon, 06 Feb 2017 13:03:40 GMT HAPServer [CC:22:3D:E3:CE:30] Pair step 3/5
Feb  6 15:03:40 RSBPI homebridge[1503]: Mon, 06 Feb 2017 13:03:40 GMT HAPServer [CC:22:3D:E3:CE:30] Pair step 4/5
Feb  6 15:03:40 RSBPI homebridge[1503]: Mon, 06 Feb 2017 13:03:40 GMT HAPServer [CC:22:3D:E3:CE:30] Pair step 5/5
Feb  6 15:03:40 RSBPI homebridge[1503]: Mon, 06 Feb 2017 13:03:40 GMT Accessory [Homebridge] Paired with client F0DDFA9D-38B6-4FE6-94C1-6B95407DF026
Feb  6 15:03:40 RSBPI homebridge[1503]: Mon, 06 Feb 2017 13:03:40 GMT EventedHTTPServer [::ffff:10.0.0.51] HTTP Response is finished
Feb  6 15:03:40 RSBPI homebridge[1503]: Mon, 06 Feb 2017 13:03:40 GMT EventedHTTPServer [::ffff:10.0.0.51] Client connection closed
Feb  6 15:03:40 RSBPI homebridge[1503]: Mon, 06 Feb 2017 13:03:40 GMT EventedHTTPServer [::ffff:10.0.0.51] HTTP connection was closed
Feb  6 15:03:40 RSBPI homebridge[1503]: Mon, 06 Feb 2017 13:03:40 GMT EventedHTTPServer [::ffff:10.0.0.51] HTTP server was closed
Feb  6 15:03:40 RSBPI homebridge[1503]: Mon, 06 Feb 2017 13:03:40 GMT EventedHTTPServer [::ffff:10.0.0.51] New connection from client
Feb  6 15:03:40 RSBPI homebridge[1503]: Mon, 06 Feb 2017 13:03:40 GMT EventedHTTPServer [::ffff:10.0.0.51] HTTP server listening on port 41380
Feb  6 15:03:40 RSBPI homebridge[1503]: Mon, 06 Feb 2017 13:03:40 GMT EventedHTTPServer [::ffff:10.0.0.51] HTTP request: /pair-verify
Feb  6 15:03:40 RSBPI homebridge[1503]: Mon, 06 Feb 2017 13:03:40 GMT HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pair-verify
Feb  6 15:03:40 RSBPI homebridge[1503]: Mon, 06 Feb 2017 13:03:40 GMT HAPServer [CC:22:3D:E3:CE:30] Pair verify step 1/2
Feb  6 15:03:40 RSBPI homebridge[1503]: Mon, 06 Feb 2017 13:03:40 GMT EventedHTTPServer [::ffff:10.0.0.51] HTTP Response is finished
Feb  6 15:03:40 RSBPI homebridge[1503]: Mon, 06 Feb 2017 13:03:40 GMT EventedHTTPServer [::ffff:10.0.0.51] HTTP request: /pair-verify
Feb  6 15:03:40 RSBPI homebridge[1503]: Mon, 06 Feb 2017 13:03:40 GMT HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pair-verify
Feb  6 15:03:40 RSBPI homebridge[1503]: Mon, 06 Feb 2017 13:03:40 GMT HAPServer [CC:22:3D:E3:CE:30] Pair verify step 2/2
Feb  6 15:03:40 RSBPI homebridge[1503]: Mon, 06 Feb 2017 13:03:40 GMT HAPServer [CC:22:3D:E3:CE:30] Client F0DDFA9D-38B6-4FE6-94C1-6B95407DF026 verification complete
Feb  6 15:03:40 RSBPI homebridge[1503]: Mon, 06 Feb 2017 13:03:40 GMT EventedHTTPServer [::ffff:10.0.0.51] HTTP Response is finished
Feb  6 15:03:40 RSBPI homebridge[1503]: Mon, 06 Feb 2017 13:03:40 GMT EventedHTTPServer [::ffff:10.0.0.51] HTTP request: /accessories
Feb  6 15:03:40 RSBPI homebridge[1503]: Mon, 06 Feb 2017 13:03:40 GMT HAPServer [CC:22:3D:E3:CE:30] HAP Request: GET /accessories
Feb  6 15:03:40 RSBPI homebridge[1503]: Mon, 06 Feb 2017 13:03:40 GMT EventedHTTPServer [::ffff:10.0.0.51] HTTP Response is finished
Feb  6 15:03:41 RSBPI homebridge[1503]: Mon, 06 Feb 2017 13:03:41 GMT EventedHTTPServer [::ffff:10.0.0.51] HTTP request: /pairings
Feb  6 15:03:41 RSBPI homebridge[1503]: Mon, 06 Feb 2017 13:03:41 GMT HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pairings
Feb  6 15:03:41 RSBPI homebridge[1503]: Mon, 06 Feb 2017 13:03:41 GMT HAPServer [CC:22:3D:E3:CE:30] Removing pairing info for client
Feb  6 15:03:41 RSBPI homebridge[1503]: Mon, 06 Feb 2017 13:03:41 GMT Accessory [Homebridge] Unpairing with client F0DDFA9D-38B6-4FE6-94C1-6B95407DF026
Feb  6 15:03:41 RSBPI homebridge[1503]: Mon, 06 Feb 2017 13:03:41 GMT EventedHTTPServer [::ffff:10.0.0.51] HTTP Response is finished
Feb  6 15:03:41 RSBPI homebridge[1503]: Mon, 06 Feb 2017 13:03:41 GMT EventedHTTPServer [::ffff:10.0.0.51] Client connection closed
Feb  6 15:03:41 RSBPI homebridge[1503]: Mon, 06 Feb 2017 13:03:41 GMT EventedHTTPServer [::ffff:10.0.0.51] HTTP connection was closed
Feb  6 15:03:41 RSBPI homebridge[1503]: Mon, 06 Feb 2017 13:03:41 GMT EventedHTTPServer [::ffff:10.0.0.51] HTTP server was closed

If I remove the delay switch accessory I could add homebridge again

**Comment by nitaybz** [comment]
maybe try updating your homebridge / node versions.

this is weird as I don't realize why the server is failing.
does it happens only with 5 delay devices or even with one?

**Comment by nitaybz** [comment]
also you talked only about the persist folder but it looks like there is an issue with the accessory, try deleting the accessory folder. that of course will force you to setup homebridge on iOS from the beginning so think about that.

**Comment by zork17** [comment]
This time I tried it only with one accessory.
It is the same when also deleting the accessories folder. In any case I need to restart setup from the beginning: This is the main problem: When I add even one DelaySwitch and restart homebridge, it is not reachable anymore and I need to remove it from the home and restart everything.

It used to work and then I added or updated some plugin (I think it was HomeAssistant which is installed on another machine) and now it doesn't work.
I removed that plugin.

Now I have:
npm list -g --depth=0
/usr/lib
├── homebridge@0.4.9
├── homebridge-delay-switch@0.0.1
├── homebridge-http-webhooks@0.0.22
├── homebridge-knx@0.3.3
├── node-gyp@3.4.0
└── npm@3.10.8

Should I update? How do you do it?

**Comment by zork17** [comment]
@nitaybz 
snowdd1 from homebridge wrote:

> Looks as if the response to HomeKit is non compliant with the delay switches. The whole bridge gets unpaired from HomeKit.
> You might try to raise the question at the delay-switch repository.

**Comment by nitaybz** [comment]
please update the latest homebridge and node....
If you install homebridge and/or plugins using npm, you can use npm to update them. https://docs.npmjs.com/cli/update

**Comment by zork17** [comment]
@nitaybz 
I ran sudo npm outdated
but nothing
I know homebridge-knx is not the latest.
I ran sudo npm -g update homebridge-knx
and it stayed on 0.3.3

Maybe the problems are related? Why it is not updating?
How do I update node? I can't see it in the list above

**Comment by nitaybz** [comment]
I tried to do some fix on the code,
please try to install the plugin with the following command:
`sudo npm install -g https://github.com/nitaybz/homebridge-delay-switch.git#fix`

**Comment by zork17** [comment]
I deleted folders persist and accessories.
Entered only one DelaySwitch in config.
Homebridge failed to start:

Feb  7 21:47:11 RSBPI homebridge[1584]: [2/7/2017, 9:47:11 PM] [CupboardDelSw] Initializing DelaySwitch accessory...
Feb  7 21:47:11 RSBPI homebridge[1584]: /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Service.js:72
Feb  7 21:47:11 RSBPI homebridge[1584]: throw new Error("Cannot add a Characteristic with the same UUID as another Characteristic in this Service: " + existing.UUID);
Feb  7 21:47:11 RSBPI homebridge[1584]: ^
Feb  7 21:47:11 RSBPI homebridge[1584]: Error: Cannot add a Characteristic with the same UUID as another Characteristic in this Service: 00000025-0000-1000-8000-0026BB765291
Feb  7 21:47:11 RSBPI homebridge[1584]: at Service.addCharacteristic (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Service.js:72:13)
Feb  7 21:47:11 RSBPI homebridge[1584]: at DelaySwitch.getServices (/usr/lib/node_modules/homebridge-delay-switch/index.js:21:15)
Feb  7 21:47:11 RSBPI homebridge[1584]: at Server._createAccessory (/usr/lib/node_modules/homebridge/lib/server.js:378:36)
Feb  7 21:47:11 RSBPI homebridge[1584]: at Server._loadAccessories (/usr/lib/node_modules/homebridge/lib/server.js:266:26)
Feb  7 21:47:11 RSBPI homebridge[1584]: at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:81:38)
Feb  7 21:47:11 RSBPI homebridge[1584]: at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:40:10)
Feb  7 21:47:11 RSBPI homebridge[1584]: at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
Feb  7 21:47:11 RSBPI homebridge[1584]: at Module._compile (module.js:556:32)
Feb  7 21:47:11 RSBPI homebridge[1584]: at Object.Module._extensions..js (module.js:565:10)
Feb  7 21:47:11 RSBPI homebridge[1584]: at Module.load (module.js:473:32)
Feb  7 21:47:11 RSBPI systemd[1]: homebridge.service: main process exited, code=exited, status=1/FAILURE

**Comment by nitaybz** [comment]
@zork17 try again to install from here:
`sudo npm install -g https://github.com/nitaybz/homebridge-delay-switch.git#fix`

**Comment by zork17** [comment]
Thank you for your help, but homebridge still crashes on startup:

Feb  8 22:26:38 RSBPI homebridge[6379]: [2/8/2017, 10:26:38 PM] [DelSwitch] Initializing DelaySwitch accessory...
Feb  8 22:26:38 RSBPI homebridge[6379]: /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/AccessoryLoader.js:95
Feb  8 22:26:38 RSBPI homebridge[6379]: var serviceUUID = json.sType;
Feb  8 22:26:38 RSBPI homebridge[6379]: ^
Feb  8 22:26:38 RSBPI homebridge[6379]: TypeError: Cannot read property 'sType' of undefined
Feb  8 22:26:38 RSBPI homebridge[6379]: at parseServiceJSON (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/AccessoryLoader.js:95:25)
Feb  8 22:26:38 RSBPI homebridge[6379]: at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/AccessoryLoader.js:63:19
Feb  8 22:26:38 RSBPI homebridge[6379]: at Array.forEach (native)
Feb  8 22:26:38 RSBPI homebridge[6379]: at Object.parseAccessoryJSON (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/AccessoryLoader.js:62:17)
Feb  8 22:26:38 RSBPI homebridge[6379]: at Server._createAccessory (/usr/lib/node_modules/homebridge/lib/server.js:385:28)
Feb  8 22:26:38 RSBPI homebridge[6379]: at Server._loadAccessories (/usr/lib/node_modules/homebridge/lib/server.js:266:26)
Feb  8 22:26:38 RSBPI homebridge[6379]: at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:81:38)
Feb  8 22:26:38 RSBPI homebridge[6379]: at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:40:10)
Feb  8 22:26:38 RSBPI homebridge[6379]: at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
Feb  8 22:26:38 RSBPI homebridge[6379]: at Module._compile (module.js:556:32)
Feb  8 22:26:38 RSBPI systemd[1]: homebridge.service: main process exited, code=exited, status=1/FAILURE

**Comment by nitaybz** [comment]
I'm not giving up, try again...

**Comment by zork17** [comment]
There is still a crash of homebridge:

Feb  9 08:23:58 RSBPI homebridge[17940]: /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/AccessoryLoader.js:95
Feb  9 08:23:58 RSBPI homebridge[17940]: var serviceUUID = json.sType;
Feb  9 08:23:58 RSBPI homebridge[17940]: ^
Feb  9 08:23:58 RSBPI homebridge[17940]: TypeError: Cannot read property 'sType' of undefined
Feb  9 08:23:58 RSBPI homebridge[17940]: at parseServiceJSON (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/AccessoryLoader.js:95:25)
Feb  9 08:23:58 RSBPI homebridge[17940]: at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/AccessoryLoader.js:63:19
Feb  9 08:23:58 RSBPI homebridge[17940]: at Array.forEach (native)
Feb  9 08:23:58 RSBPI homebridge[17940]: at Object.parseAccessoryJSON (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/AccessoryLoader.js:62:17)
Feb  9 08:23:58 RSBPI homebridge[17940]: at Server._createAccessory (/usr/lib/node_modules/homebridge/lib/server.js:385:28)
Feb  9 08:23:58 RSBPI homebridge[17940]: at Server._loadAccessories (/usr/lib/node_modules/homebridge/lib/server.js:266:26)
Feb  9 08:23:58 RSBPI homebridge[17940]: at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:81:38)
Feb  9 08:23:58 RSBPI homebridge[17940]: at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:40:10)
Feb  9 08:23:58 RSBPI homebridge[17940]: at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
Feb  9 08:23:58 RSBPI homebridge[17940]: at Module._compile (module.js:556:32)
Feb  9 08:23:58 RSBPI systemd[1]: homebridge.service: main process exited, code=exited, status=1/FAILURE

Thank you for your effort!

**Comment by nitaybz** [comment]
I seriously think that you have some kind of installation problem in your homebridge.... how did you install it?

**Comment by zork17** [comment]
I am not an expert, but I installed the whole raspberry pi and the OS and homebridge according to a few articles I found online. Everything else is working well. I have 95 devices using KNX and I had LIFX lamps working as well and also HTTP-WEBKOOKS.
I updated the above plugins using for example:
sudo npm -g update homebridge-knx
and the update succeeded and everything is working.

Can you see where is the problems? Where it is crashing?
Maybe you can add debug messages so you can see where are the problems?
Before the last crashes (the special code you wrote for me to check) I could not add Homebridge to the IOS Home app.

**Comment by zork17** [comment]
@nitaybz 
Did you give up?
Do you know of another way to achieve a delay?

**Comment by nitaybz** [comment]
no I'm sorry I went to a vacation.

try updating homebridge with `sudo npm -g update homebridge`
something is really wrong with your set up I believe
I also think that when you said you deleted your persist and accessory folder you didn't delete the right one.

I have to know exactly how you installed homebridge, did you set it to lunch at boot? if so, your persist folder is located somewhere else... please give me more information regarding your homebridge installation and I will try my best to help.

**Comment by zork17** [comment]
I already done the update for homebridge and all plugins I installed.
now I get:

> sudo npm outdated -g
> Package  Current  Wanted  Latest  Location
> npm        4.1.2   4.1.2   4.2.0
> 

After I installed homebridge I changed it to boot on startup and indeed the place for the config.json and knx_config.json files and persist and accessories folders moved to /var/homebridge.
I know the deletion of the folders works because without it, it doesn't.

I tried to uninstall delay-switch and install again the regular version but still there is the same problem: It causes homebridge to be inaccessible from IOS and so I need to remove it from home and delete the 2 folders and start everything all over again.

**Comment by nitaybz** [comment]
I don't understand why your homebridge is in knx version, I'm really not familiar with this type of homebridge. My homebridge only contains 1 config file

**Comment by zork17** [comment]
My homebridge is not IN knx version.
There is a config file for the KNX plugin in the homebridge folder.
This is the normal way to put it. See here: https://github.com/snowdd1/homebridge-knx

**Comment by peros550** [comment]
I just wanted to report that I too had issues with my setup when I started using this plugin. By the moment I had it set up, my accessories became unresponsive in Home app. Then I removed the configuration related to this plugin and everything went back in normal. 

My homebridge runs in Rpi3. Everything was up to date.

**Comment by peros550** [comment]
In my case, I was able to install the plugin and use it but I had first to remove Homebridge from the Home app and add it again. If Homebridge has other plugins and automations, rooms,   removing it needs you to setup all over again which is a pain in the ass if you system is large.

If I didn't do the remove-add action, Homebridge service was running normally, with the Delay-Switch installed (was able to view live log messages) but no accessory was responding within the Home app. 

I hope you can do something about it because it's a pretty handy plugin. If you need me to provide you with any kind of additional information for better troubleshooting, just let me know. 

Note: all the above happened in exactly the same manner in two different homebridge configurations I maintain in two different houses. 

Thanks

**Comment by nitaybz** [comment]
try install the latest...

**Comment by nitaybz** [comment]
Fixed with the last version
