### ISSUE TITLE
Can switch be used for this scenario?

### ISSUE THREAD

**Issue by x5nder** [nitaybz/homebridge-delay-switch#20]
I have a Xiaomi Door & Window Sensor, and Honeywell Evotherm radiator knobs. I'm a bit unclear if (and how) this switch can be used to help me with the following behavior:

"When door sensor is OPEN **for longer than 3 minutes**, disable heating."

A rule without the 'longer than' is easy, but I don't want Honeywell to keep receiving on/off commands every time I open the sliding door to quickly grab something outside -- only when the door is open for a longer period.

Is this possible with homebridge-delay-switch, and if yes, what's the easiest way?

**Comment by nitaybz** [comment]
Create a sensor names "Door Heating Delay" (for example).
Assuming you're using motion sensor as well (normal configuration), create the following automations: 
IF > Door Opens > THEN > Turn On "Door Heating Delay"
IF > "Door Heating Delay trigger" (motion sensor) Detects Motion > THEN > Turn Off Heating
IF > Door Closes > THEN > Turn Off "Door Heating Delay" (this will make sure not to trigger when the door closes before the time frame)

hope it helps and works as expected

UPDATE: the word "longer" is not really accurate, as you would close the Heating if it reaches 3 minutes, and no longer

**Comment by x5nder** [comment]
Thanks (and yes, that's a valid remark, I should have said 'when door sensor is OPEN for 3 minutes...').

**Comment by nitaybz** [comment]
let me know if it did the trick
