### ISSUE TITLE
[FEATURE] Eve App 4.2 Issue with homebridge-delay-switches 

### ISSUE THREAD

**Issue by DJay-X** [nitaybz/homebridge-delay-switch#23]
@nitaybz 
The lates Eve for HomeKit App v4.2 is causing issues with several Homebridge Plugins.
They changed something so that the serial number of a device is linked somehow in the background. This was not in the previous Eve versions.
Problems causing now like described here.
https://github.com/homebridge/homebridge/issues/2503

So all devices/switches created by homebridge-delay-switch can't be sorted anymore, can't get an individual icon by each switch, and can't starred individually for favorite screen.

![RPReplay_Final1587217613 2020-04-18 15_50_01](https://user-images.githubusercontent.com/3874239/79639618-34893300-818d-11ea-8606-c685f442d115.gif)

Do you see a solution to fix this "Eve" Issue, by changing something in your plugin?
Maybe adding something like a "unique_serial": "xxxx" for each sensor, manually in the config.json or automatically by the plugin.

@nicoduj already found a solution for his plugin.
https://github.com/nicoduj/homebridge-harmony/issues/249

And @pponce also already crated a fix to get `"unique_serial":` to work around the Eve App issue.
https://github.com/pponce/homebridge-script2/issues/25

Thanks in advance for your work and the time you are investing.

**Comment by nitaybz** [comment]
Hey!
I really appreciate your fully detailed issue and solution found!

I just had my son born last week but I'll try to find the time to fix it :)

**Comment by DJay-X** [comment]
Hey. Thanks for your reply.
First and foremost, congratulations and all the best for your family. Wishing you all the best and besides the exhausting times also a lot of joy. 😉❤️

Maybe you will find a little positive distraction by working on your plugin, to get rid of the Eve App serial number Issue. 😬

Wouldn't want to miss your plugin. 

Please of course let me know, If I as user, can help with something.

Thanks again for your time and keeping the plugin alive. 👍

**Comment by nitaybz** [comment]
@DJay-X it should be fixed now.. but you'll probably have to recreate the accessories.
let me know how it goes...

**Comment by DJay-X** [comment]
Thanks a lot.
Seems to automatically generate a unique UUID for each DelaySwitch.
Looks good to me. 👍 

Thanks again and all the best to you and your family. 😌🙏

![Napkin 02 05 20, 9 00 34 AM](https://user-images.githubusercontent.com/3874239/80857578-88971b80-8c53-11ea-96f9-773822c24362.png)

**Comment by nitaybz** [comment]
Thank you! Glad I could help😊
