### ISSUE TITLE
Cannot load after latest update -Cannot read property 'hap' of undefined-

### ISSUE THREAD

**Issue by dcaccount** [nitaybz/homebridge-delay-switch#25]
Hello,
I have just updated Delay Switch and I won't load any longer and it prevents Homebridge from loading. 

The error I have is:

`[DelayGate] Initializing DelaySwitch accessory...
mag 12 13:59:57 rpinvr131 homebridge[2074]: [2020-5-12 13:59:57] TypeError: Cannot read property 'hap' of undefined
mag 12 13:59:57 rpinvr131 homebridge[2074]:     at new delaySwitch (/usr/lib/node_modules/homebridge-delay-switch/index.js:13:23)
mag 12 13:59:57 rpinvr131 homebridge[2074]:     at Server._loadAccessories (/usr/lib/node_modules/homebridge/lib/server.js:308:29)
mag 12 13:59:57 rpinvr131 homebridge[2074]:     at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:91:38)
mag 12 13:59:57 rpinvr131 homebridge[2074]:     at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:59:10)
mag 12 13:59:57 rpinvr131 homebridge[2074]:     at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
mag 12 13:59:57 rpinvr131 homebridge[2074]:     at Module._compile (internal/modules/cjs/loader.js:816:30)
mag 12 13:59:57 rpinvr131 homebridge[2074]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
mag 12 13:59:57 rpinvr131 homebridge[2074]:     at Module.load (internal/modules/cjs/loader.js:685:32)
mag 12 13:59:57 rpinvr131 homebridge[2074]:     at Function.Module._load (internal/modules/cjs/loader.js:620:12)
mag 12 13:59:57 rpinvr131 homebridge[2074]:     at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)`

What shall I do, please help!
Thanks,
Dan

**Comment by nitaybz** [comment]
Please update HomeBridge
