### ISSUE TITLE
Documentation Unclear

### ISSUE THREAD

**Issue by jsiegenthaler** [nitaybz/homebridge-delay-switch#27]
Hello

A great plugin but the documentation is unclear.
What unit of measure applies to the "delay" value? Is it milliseconds, seconds, minutes, hours, ticks... ??
Perhaps you could update the documentation to clearly state what the unit is.

**Comment by nitaybz** [comment]
it is mentioned in the docs:
![image](https://user-images.githubusercontent.com/16838394/88838808-bf44e980-d1e2-11ea-8ddb-f89c9e4b88d0.png)

but I'll make sure to add it in the sample config so it will be more clear.

thanks for the notice.

**Comment by jsiegenthaler** [comment]
Thanks @nitaybz for being so responsive, great work!
