### ISSUE TITLE
Typos in the Documentation

### ISSUE THREAD

**Issue by jsiegenthaler** [nitaybz/homebridge-delay-switch#28]
Reading this page I see a number of typos:
https://www.npmjs.com/package/homebridge-delay-switch

Text "This can be achieved by setting an automation to turn ON a **lightand** the delay switch"
Incorrect: **lightand**
Correct: **light and**

Text "when the dedicated delay motion sensor is **triggers** (or delay switch is turned OFF)."
Incorrect:  **triggers**
Correct:  **triggered**

Text "Why **Adding** Motion Sensor?"
Incorrect:  **Adding**
Correct:  **Add a**

Text "How it works? you can set "
Incorrect:  **How** it works? **you** can set 
Correct: **How does** it works? **You** can set

**Comment by nitaybz** [comment]
English is not my native language, so thanks for the corrections :)
it's fixed now
