### ISSUE TITLE
Enhancement request: Config option to start ON

### ISSUE THREAD

**Issue by JimDog546** [nitaybz/homebridge-delay-switch#29]
Provide a config.json flag that makes the default state of the switch ON when Homebridge starts.  Also start the delay timer.

**Comment by nitaybz** [comment]
check the latest 2.2.0

**Comment by JimDog546** [comment]
Seems to be working as expected.  Exactly what I needed.  Appreciate the addition and quick turnaround!

**Comment by raixer** [comment]
this function "seems" to be working. However, I have an automation that runs when the switch turns off and that isn't getting triggered after a real homebridge restart.
I have the delay switch configured with a delay of 3 minutes and to startOnReboot. All looks fine and the timer runs but when the timer is up the automation doesn't get triggered. Now if I manually toggle the delay switch on, after 3 minutes the automation gets triggered.
So I am at a lost here on what may be happening. I even verified in the Home app that the switch appears on before the timer is up so dunno why the automation isn't getting triggered after a real homebridge restart.

**Comment by raixer** [comment]
For whoever has the same problem..
As a workaround this works a lot better if you leave disableSensor false and use the sensor as the automation trigger.

**Comment by nitaybz** [comment]
This is what I wanted to say, why not using the motion sensor trigger? It is usually more reliable.
