### ISSUE TITLE
Stopping a delay once it's started?

### ISSUE THREAD

**Issue by jaquesp** [nitaybz/homebridge-delay-switch#3]
Hi there, thanks for this plugin - it's very useful. I'm using it to turn off a light based on a delay. Effectively when a light is turned on, it triggers the delay switch which when shut off turns the light off again.

However, I'm seeing some curious behaviour. Normally, the delay switch is triggered and starts it's countdown. On a couple of occurrences I have manually turned the switch off, expecting the timer to also stop. In the example below, the light has actually been activated again within the original countdown, and i would expect this to reactivate the timer - restarting the original countdown. However, what I see is that the original timer has not stopped, and still switches off after the delay, and a second is created, also switching off again after the configured delay:

```
Feb  2 16:25:58 raspberrypi homebridge[21857]: [2/2/2017, 4:25:58 PM] [Porch_DelaySwitch1] Setting switch to 1
Feb  2 16:26:07 raspberrypi homebridge[21857]: [2/2/2017, 4:26:07 PM] [Porch_DelaySwitch1] Setting switch to 0
Feb  2 16:26:08 raspberrypi homebridge[21857]: [2/2/2017, 4:26:08 PM] [Porch_DelaySwitch1] Setting switch to 1
Feb  2 16:40:58 raspberrypi homebridge[21857]: [2/2/2017, 4:40:58 PM] [Porch_DelaySwitch1] Setting switch to false
Feb  2 16:41:08 raspberrypi homebridge[21857]: [2/2/2017, 4:41:08 PM] [Porch_DelaySwitch1] Setting switch to false
```

Is this expected behaviour? Is there anyway I can "interrupt" a timer once it's started?

Thanks in advance!

**Comment by nitaybz** [comment]
Hi @jaquesp , my pleasure to help you automate your house better. 
This behavior is expected and there is no way you can interrupt the timer, it's running in the background and it built this way so while using this switch it won't stuck the app until the process is finishes.
For example: if I the switched is turned on and I'll show the process in home app it will show a loading sign until the timer is off, in some cases when a long delay is required, you wouldn't want the app to be stuck on loading until timer is done.

Hope it makes sense, if someone thinks they can solve it better I will be happy to modify the code.

**Comment by jaquesp** [comment]
Thanks for the quick response and this makes sense with what I'm seeing.
However this does mean that the display of the switch in the home app is often out of sync with what's actually happening in the background.

In fact - if i had the skill to code this I think there a few improvements which could be made:

1. Make this a contact sensor or something similar that doesn't let you interact with it via the home app - it just shows the status of the current timer.

2. Alternatively, allow the switch in the app to stop the timer(s) in the background.

3. Additionally, the switch in the home app should replicate the current status of the timer(s). So, in the example when a timer is started, stopped and then started again, the switch should stay on until the last timer for that switch has completed?

I hope those make sense.

Thanks again for your consideration!

**Comment by nitaybz** [comment]
your suggestion number 1 will not add any values, cause you can just leave this switch in a different room so you will just not change anything with it, and therefor  it's not worth on working on it to change it to a sensor. - you'll still not be able to do what you wanted in the first place.

suggestion 2 is what you actually wanted and I'll think of a way to surpass this though this plugin was meant to be used only in automations, not changing it manually.
also remember that if you'll stop (turn off) the timer(switch) your delayed automation will start anyway. maybe if i can realize better what exactly your intentions with this plugin I can help you better.

suggestion 3 - the plugin is already doing it, it will be on when the timer start and will turn off when  the timer stops, but for stopping the timer - see answer 2

**Comment by jaquesp** [comment]
This is the use case I have - I hope this explains what I'm trying to achieve

1. 15:00 Arrive home - porch light switches on, delay switch also commence for 15 mins
2. 15:05 Leave home - all lights get turned off, delay switch still has 10 minutes remaining
3. 15:10 Arrive home - porch light gets switched on again, another timer starts for 15 minutes
4. 15:15 - First occurrence of delay switch turns off the porch light after just 5 minutes.Home app shows the timer switch off
5. 15:25 - Second occurrence of delays switch attempts to turn off the porch light again - no change in app or lights.

What would be ideal is if at Stage 4 - this timer does not turn off the light. The delay actually only finishes at Stage 5 (after all times have finished) at which point the automation is fired.

I hope this makes sense - thanks again for considering this problem!

**Comment by nitaybz** [comment]
got it... I will see what I can do

**Comment by jaquesp** [comment]
Thanks @nitaybz !!

**Comment by nitaybz** [comment]
@jaquesp i think I found an easy fix... try to install from here and let me know if it did the trick:
`sudo npm install -g https://github.com/nitaybz/homebridge-delay-switch.git#off`

when off command is sent, it should kill the time out.

**Comment by jaquesp** [comment]
Thanks so much! I'll try this today!

**Comment by jaquesp** [comment]
This is excellent and works like a charm! Thanks very much! Out of interest, what change did you make to resolve it?

**Comment by nitaybz** [comment]
I used the timeout in a variable, then used it to stop the timer if an OFF command is sent.
thanks for pushing me to find that and upgrading the plugin, makes a lot of sense now!

**Comment by jaquesp** [comment]
Great work - thanks ever so much for looking into this. I think it's now a much more usable solution to the problem! Thanks!
