### ISSUE TITLE
Settings Broken in Config UI

### ISSUE THREAD

**Issue by rivertonrock** [nitaybz/homebridge-delay-switch#30]
I’m no longer able to edit the Settings of the plugin. All of the existing accessories are expanded, and there is no option to add an accessory block. I believe this started with the latest Update, but I’m not 100% positive. However, I’ve noticed the same behavior on two instances: one running the official Raspberry Pi HomeBridge image, and one in a Docker container. Let me know if you need any additional info. 

![F0F49923-1A0C-4D67-AECE-2910D81FD43D](https://user-images.githubusercontent.com/28568657/88937294-960b7400-d249-11ea-8b54-aa1f986de30e.png)

**Comment by nitaybz** [comment]
how did you add more accessories before that?

**Comment by rivertonrock** [comment]
On the vanilla image, most were added before there was a Settings option, and a few were added after. On the Docker image, I just now created the first and only accessory, and I’m seeing the same issue: unable to collapse existing accessories or Add Accessory Block.

**Comment by nitaybz** [comment]
I think what you are referring to is the behaviour of a platform, and this accessory was never a platform... you can always edit it from the config and add more devices there.
I'm not using the UI often so i'm not sure how it's suppose to behave but adding an accessory from the settings is in platform as far as I know

**Comment by rivertonrock** [comment]
That makes sense; thank you for clarifying. Closing this Issue.

**Comment by nitaybz** [comment]
@rivertonrock Hey Man, you were 100% right.. I did some digging and I actually had something there that prevents this button from appearing...
it should be fixed on version 2.2.3.

funny thing is, it was always like this apparently for this plugin since i made it compatible with the UI

**Comment by rivertonrock** [comment]
Awesome! Thanks for the follow-up!
