### ISSUE TITLE
Can't remove delay switch from favorites

### ISSUE THREAD

**Issue by galzil** [nitaybz/homebridge-delay-switch#31]
Thanks for the very useful plugin.
A small issue is that I can't set the Favorites toggle off when the switch is configured from within the **hoobs** ui.
it adds a small section to the config that creates some bug.
`"plugin_map": {
                "plugin_name": "homebridge-delay-switch",
                "index": 0
            },`
If I remove that section, the problem is resolved.

I have a single switch set:
`{
            "accessory": "DelaySwitch",
            "plugin_map": {
                "plugin_name": "homebridge-delay-switch",
                "index": 0
            },
            "delay": 5000,
            "disableSensor": false,
            "startOnReboot": false,
            "name": "5 Seconds"
        }`

**Comment by nitaybz** [comment]
It's an apple bug as far as I know... try to show the accessory as a separate tile and try again

**Comment by galzil** [comment]
The problem resolved when I removed the extra lines that hoobs adds. 
Maybe it's a hoobs issue

**Comment by homeconnector** [comment]
Works ok for me.  Might be a caching issue.  If so, you need to delete the bridge and remove cache, and readd it
