### ISSUE TITLE
Sensor and Switch not responding to automations

### ISSUE THREAD

**Issue by HumanSkunk** [nitaybz/homebridge-delay-switch#34]
I am currently running Homebridge 1.2.3 and I am having issues With iOS14 and HomeKit. Before updating I didnt have any issues with this plugin but since updating the hue motion sensor I have driving the delay switch is detecting motion but isn't engaging the switch in homebridge. Likewise at the end of the timer sometimes the motion sensor in the plugin triggers in homebridge but doesn't toggle the actual lights back off.

Unsure what the cause is and I think some change in iOS14 has broken how some plugins communicate. Unsure if any of your other users are having the same problem.

**Comment by jsiegenthaler** [comment]
The Homebridge guys say either upgrade to 1.3.0-beta, or downgrade to 1.1.6. No-one should be using 1.2.3 because of some issues with it.

**Comment by HumanSkunk** [comment]
> The Homebridge guys say either upgrade to 1.3.0-beta, or downgrade to 1.1.6. No-one should be using 1.2.3 because of some issues with it.

Thanks. I moved away from Homebridge to Home Assistant about a week ago as u was still experiencing issues with 1.1.6 and the betas. Things are working perfectly under Home Assistant. Fingers crossed they work out what the cause is...
