### ISSUE TITLE
Request: Update Manufacturer And Model with meaningful information

### ISSUE THREAD

**Issue by jsiegenthaler** [nitaybz/homebridge-delay-switch#35]
Currently, Manufacturer and Model show the following in the HomeKit app:
Manufacturer = "Delay Manufacturer"
Model = "Delay Model" 

It would look smarter if you had:
Manufacturer = "Delay Switch"
Model = "Delay Nms", where N = the programmed delay time in milliseconds, e.g.: "Delay 5000ms"

This would look smarter and allow the user in Homebridge to see what delay was programmed for each switch he uses

**Comment by nitaybz** [comment]
Good Idea!
✅ DONE in the latest version
