### ISSUE TITLE
New Fonction :

### ISSUE THREAD

**Issue by Stewart06** [nitaybz/homebridge-delay-switch#36]
Bonjour, j'apprécie énormément votre plugin qui gérés actuellement tous mes détecteurs des pièces, car Apple géré très mal les minuteries, surtout les couloirs avec beaucoup de passage. Et ce plugin les gère à merveilleux donc bravo et un grand merci. Cela étant j'ai une requête sur la possibilité de pouvoir verrouiller une minuterie quand on le souhaite.
Explication : Par moment ma femme accroche le linge dans un couloir et celui-ci ne fait que s'éteindre malgré sa présence et le fait de bouger. J'ai essayé à plusieurs reprises de créer des règles qui relancerai la minuterie en boucle après avoir appuyé sur un interrupteur mais malheureusement cela ne fonctionne pas.

Résolution : Le top serai de rajouter une fonction à votre plugin qui activerai ou désactiverai la minuterie grâce à un interrupteur. Un peu comme si on pouvait mettre la minuterie en AUTO ou bien en marche forcé, ou ON et OFF.

J'espère que mon explication est assez clair et que cela pourrait vous donner l'envie de créer cette fonction afin de pouvoir inhibé la minuterie ou pas.

Hello, I really appreciate your plugin which currently manages all my room detectors, because Apple has very poorly managed the timers, especially the corridors with a lot of traffic. And this plugin manages them at wonderful so well done and a big thank you. However, I have a query on the possibility of being able to lock a timer when desired.
Explanation: At times my wife hangs the laundry in a hallway and it just goes out despite its presence and the fact of moving. I have tried several times to create rules that will restart the loop timer after pressing a switch but unfortunately it does not work.

Resolution: The best will be to add a function to your plugin which will activate or deactivate the timer using a switch. A bit as if we could put the timer in AUTO or forced operation, or ON and OFF.

Hope my explanation is pretty clear and it might make you want to create this function so that you can inhibit the timer or not.

**Comment by nitaybz** [comment]
Hey, thanks for the compliments...
The function you're talking about is already implemented in plugin.
By turning off the delay switch, the timer should stop. Also, if you turn it on again it should restart the timer... it works flawlessly to me when I'm moving in a room and my delay switch always restarts.

**Comment by fentonmatt** [comment]
@nitaybz I too am curious on this function as the same thing happens to me. I love this plugin but cannot get it to work more than the desired time I have set. I have it set for my lights to turn off after 15 minutes if no motion but watching the logs it does not show restart of the timer every time in my case motion is detected. And so every time after 15 minutes it turns off which I'm trying to avoid and only have happen when no motion is detected but turns off even when there is. Does not seem to be resetting timer every time motion is detected which I have it setup to do in my automations. Any thoughts?

**Comment by jsiegenthaler** [comment]
@fentonmatt 
Check your config. What you need to do is have a simple automation that turns ON the delay switch every time motion is detected, and also turns ON the delay switch every time motion is NOT detected.
This way the delay switch is turned on at start of motion (and timer starts), and also turned on again at end of motion (and timer is reset and starts again).
This means the delay time is the time AFTER the motion ends, and always resets when any new motion starts or stops.
This is what I do and it works well.

**Comment by xrust83** [comment]
> @fentonmatt
> Проверьте свою конфигурацию. Что вам нужно сделать, так это иметь простую автоматизацию, которая включает переключатель задержки каждый раз при обнаружении движения, а также включает переключатель задержки каждый раз, когда движение НЕ обнаружено.
> Таким образом, переключатель задержки включается в начале движения (и запускается таймер), а также снова включается в конце движения (и таймер сбрасывается и запускается снова).
> Это означает, что время задержки - это время ПОСЛЕ окончания движения, и оно всегда сбрасывается, когда начинается или останавливается любое новое движение.
> Это то, что я делаю, и это хорошо работает.

Interesting idea. Share a screenshot of how it is configured, whether it is two automation or one automation
