### ISSUE TITLE
Motion Sensor Timer Going off After Switch Turned off

### ISSUE THREAD

**Issue by adude007** [nitaybz/homebridge-delay-switch#37]
Using homebridge delay switch V2.2.6: When my automation turns off the dummy switch the timer continues to run and causes the motion sensor to detect motion. Logs indicate that the timer is stopped.

Using homebridge V1.2.0

**Comment by nitaybz** [comment]
first of all, homebridge 1.2 is unstable for as much as I know so I suggest upgrading or downgrading to 1.1.6
also... I need more information or logs...
you said it indicate the timer is stopped... do you see a log that tells you "Triggering Motion Sensor" after the stopping indication?

**Comment by adude007** [comment]
I read about the 1.2 stability issue and thought it was specific to 1.2.3. I can try downgrading. However, I only upgraded to 1.2.0 because my 1.1.6 install would no longer get picked up by my phones.

I don't see anything in the log that says triggering the sensor. I am however consistently getting a notification that the motion detector has detected motion. 

[11/2/2020, 2:51:19 PM] [Garage Left Open] Starting the Timer
[11/2/2020, 2:51:29 PM] [myQ] Holmstead: Closing.
[11/2/2020, 2:51:42 PM] [myQ] Holmstead: Closed.
[11/2/2020, 2:51:42 PM] [Garage Left Open] Stopping the Timer
[11/2/2020, 4:06:49 PM] [TplinkSmarthome] New Device Online: [TP-LINK_Smart Switch_00BD] plug [8006AD674819DEB4198806946D48E2421D5BEB0A] 192.168.0.24 9999

**Comment by adude007** [comment]
I was able to downgrade and get homebridge 1.1.6 working again. Delay sensor appears to be work as designed now.
