### ISSUE TITLE
Timers does not complete

### ISSUE THREAD

**Issue by gdotp01** [nitaybz/homebridge-delay-switch#38]
Hi
Love the plug-in and use it quite a lot. However recently I’ve noticed that the timer does not actually count down to zero every time, it seems to stop at a random time meaning the switch never turns off.  I’ve taken a picture from within eve that shows it’s stuck at 37 seconds, this was from it triggering 
![4BBD85A5-933B-4592-B5CA-0AD9DFF6CB38](https://user-images.githubusercontent.com/50060482/100717601-29001a80-33b2-11eb-993b-d5625223ae1d.png)

**Comment by nitaybz** [comment]
unfortunately what you're showing me is not part of my plugin... I don't have any Eve integration to show remaining time...
you are probably using a fork
