### ISSUE TITLE
prevent combined switch/sensor accessory?

### ISSUE THREAD

**Issue by seansweda** [nitaybz/homebridge-delay-switch#40]
After upgrading to ios 14 Home now presents the switch/sensor as a combined accessory with no way to separate them.  This means it is no longer possible to simply tap on the accessory in Home to flip the switch, you must first open the combined accessory and then flip the switch.  If you configure the delay switch without a sensor then simply tapping on the switch in Home toggles on/off, so it is obvious that the combined accessory is the issue.

Is it possible to register the switch and sensor in a way that prevents homekit from combining them in Home?

**Comment by nitaybz** [comment]
Just go into the accessory in HomeKit, scroll down to its settings and click on "Show as separate tiles"

**Comment by seansweda** [comment]
Yes that worked in ios 13, do not see that option in ios 14.

**Comment by nitaybz** [comment]
I just checked and can confirm you are right...
But unfortunately, because this plugin is an accessory plugin, I can't break services into separate accessories.

Sorry but I can't fix it... hopefully Apple will in future versions.

**Comment by seansweda** [comment]
Had a bad feeling that was going to be the case.  Yet another awful Apple UI decision.  Thanks, I'll close.
