### ISSUE TITLE
Request: Sensor triggering multiple times

### ISSUE THREAD

**Issue by caiotadashi** [nitaybz/homebridge-delay-switch#41]
Hey!

Thank you for the plugin. I'm using your plugin to warn when somebody left my garage door opened.
So, here's my suggestion: A option that the switch don't turn off automatically and the motion sensor triggers every x seconds while the switch is on.
Is it possible?

Thank you!

**Comment by jsiegenthaler** [comment]
You can do this with 2 x delay switches:
DelaySwitch1: Runs for X minutes after garage door opens, eg: 10 minutes. When it finishes, it checks if the door is still open, and if so, turns on DelaySwitch2
DelaySwitch2: runs for 2 minutes, sending you a notification from the moion sensor when it fires. Then use an automation triggered by DelaySwitch2 motion sensor: check if garage door closed. If closed, turn off DelaySwitch2. If not, turn on DelaySwitch2 again. This restarts the DelaySwitch2 timer, and repeats the cycle.

So DelaySwitch1 gives you time to open the door, drive the car in or out, and close the door normally.
And DelaySwitch2 is a continuous 2 minute repeating notification to tell you the door was left open longer than you would like.

**Comment by nitaybz** [comment]
couldn't describe it better than @jsiegenthaler ...
using a few delay sensor with or without shortcuts automations you can do powerful things... I wouldn't want to destroy the simplicity of the plugin but rather let people imagination create their own needed automations.
closing

**Comment by jsiegenthaler** [comment]
@nitaybz Actually this raises a good point: can you let the user choose what type of sensor will fire at the end of the timer? I'll open a new issue to track it better....
