### ISSUE TITLE
Problem on usage

### ISSUE THREAD

**Issue by Stef1972** [nitaybz/homebridge-delay-switch#46]
I'm running homebridge 1.3.2 and IOS 14.
I have created and automation to light a bulb on with a delay.
The automation said to tun the bulb on when the sensor is active
When I turn the delay switch on, after the time I decided, the movement sensor trigged and a notification is sent to my iPhone but the bulb is not turned on?

what I'm doing wrong ?

**Comment by nitaybz** [comment]
please provide screenshots of your automations, I can't really understand if you set them correctly

**Comment by nitaybz** [comment]
closed due to no response
