### ISSUE TITLE
Add onUrl and offUrl actions

### ISSUE THREAD

**Issue by jsiegenthaler** [nitaybz/homebridge-delay-switch#48]
I'm hunting for a plugin that will call a url when a switch is turned ON, and again when the switch is turned OFF

I'd love to see this added to the delay switch

Can you add a config item:
onUrl: "http://the.url.to.call.when.switch.turns.on"
offUrl: "http://the.url.to.call.when.switch.turns.off"

This would allow me to use the delay switch to trigger a wifi-driven wall switch and do homekit automation independent controls via simple urls

**Comment by nitaybz** [comment]
you can easily use homebridge-http-switch plugin (or other http plugins) to achieve what you need... that's out of this plugin scope
