### ISSUE TITLE
Plugin no longer working on iOS 15

### ISSUE THREAD

**Issue by FranciRoosters** [nitaybz/homebridge-delay-switch#49]
Hello, ever since I’ve updated my iPhone 12 to iOS 15, the plugin no longer works. When I used to come back home and enter the geofence, my HomePod mini would announce a custom track I made specifically for when returning home. While the switch activates, the HomePod mini doesn’t play the custom track back. I have other automations based on custom tracks and they work fine. What should I so to fix this? Thanks so much for your support and hard work on the plugin.

**Comment by jsiegenthaler** [comment]
Working fine for me on iOS 15, 15.1, 15.2 and 15.2.1
I wonder if your geolocation issue might be another issue.

**Comment by nitaybz** [comment]
not a plugin issue
