### ISSUE TITLE
Add Ability To Remove From Home Status

### ISSUE THREAD

**Issue by BananimusPrime** [nitaybz/homebridge-delay-switch#52]
Hey, I love this plugin - it fills a massive hole in the default HomeKit functionality so thank you very much. One small thing would be to add the functionality of removing the switch from the Home Status. This way, it doesn’t show up on the Home app main page when triggered, it just stays hidden. I also use homebridge-dummy for similar switches and it can be turned off in the Home Status, so I hope it’s not too difficult to implement.

Thanks!

**Comment by jsiegenthaler** [comment]
That’s a standard HomeKit capability. Nothing to do with the plug-in.

**Comment by BananimusPrime** [comment]
> That’s a standard HomeKit capability. Nothing to do with the plug-in.
> […](#)

I'm not sure I understand what you mean? I am unable to remove your plug in from the Home Status, but I am able to remove similar switches from a different homebridge plugin.

**Comment by jsiegenthaler** [comment]
Home > (accessory) > Settings > Status > Include in Home Status

This exists for each and every accessory. It is a Home app setting, not a feature or function provided by the accessory. 

If you are using the delay switch as a grouped accessory containing switch and motion sensor, then you need to navigate to each accessory within the group to set the **Include in Home Status** setting
