### ISSUE TITLE
Motion sensors are no longer displayed

### ISSUE THREAD

**Issue by fabiovit** [nitaybz/homebridge-delay-switch#54]
Hello, with the latest update (via Hoobs) in the homekit the motion sensors are no longer displayed

**Comment by mcooper333** [comment]
Second this - had the same issue

**Comment by neroroxxx** [comment]
Same here

**Comment by neroroxxx** [comment]
My workaround was to change the sensor to ocupancy restarting then to motion and it shows up again

**Comment by Pblondin123** [comment]
same here took me a few days to figure it out, my workaround was to flip sensor state them all (it generated HB severe errors when running after), then i removed the flip sensor state on them all :-(

**Comment by fabiovit** [comment]
> My workaround was to change the sensor to ocupancy restarting then to motion and it shows up again

I tried but without success.

**Comment by fabiovit** [comment]
This plugin is essential for me because I use it to prevent my homekit from asking for confirmation on certain actions. Example when I arrive at home, a button created with a delay switch is activated which opens the overhead door and removes the alarm. Or other automations, such as closing the door after 60 seconds. I went back to 2.2.6.

**Comment by niels-vd** [comment]
I have the same issue, only a downgrade made the motion sensors work again

**Comment by TzachiGuetta** [comment]
@nitaybz ?

**Comment by benoitvinc** [comment]
Simply add the line sensorType with the value motion in the advance config for your timer :  

{
    "accessories": [
        {
            "name": "Washer",
            "delay": 4500000,
            "sensorType": "motion",
            "accessory": "DelaySwitch",
            "plugin_map": {
                "plugin_name": "homebridge-delay-switch"
            }
        },

**Comment by nitaybz** [comment]
try the latest version, it should be fixed for all of you even if you don't change the config now...

sorry for the trouble guys 😅

**Comment by niels-vd** [comment]
> 

No prob! Thanks for fixing it!

**Comment by TzachiGuetta** [comment]
Thank you!

**Comment by wapster182** [comment]
Such things always remind me why I do not want to update any HB plugins, left the house and lights on all day because the trigger to shut them off was not there. The automations in HomeKit where just faded, not even there anymore 😂
I also has the problem that the motion sensors where not displayed even with newest version. A complete server restart (not service) solved it for me!
Anyways, thanks for the update and the plugin!
