### ISSUE TITLE
Deprecation Warning

### ISSUE THREAD

**Issue by scottleestrange** [nitaybz/homebridge-delay-switch#56]
3/23/2022, 12:44:58 PMDelay Switch BridgeERROR(node:29914) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./helpers/" in the "exports" field module resolution of the package at /usr/lib/hoobsd/node_modules/es-abstract/package.json.
3/23/2022, 12:44:58 PMDelay Switch BridgeERROR(node:29914) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./helpers/" in the "exports" field module resolution of the package at /usr/lib/hoobsd/node_modules/es-abstract/package.json.
3/23/2022, 12:44:58 PMDelay Switch BridgeERRORUpdate this package.json to use a subpath pattern like "./helpers/*".
3/23/2022, 12:44:58 PMDelay Switch BridgeERRORUpdate this package.json to use a subpath pattern like "./helpers/*".
3/23/2022, 12:44:58 PMDelay Switch BridgeERROR(Use `node --trace-deprecation ...` to show where the warning was created)
3/23/2022, 12:44:58 PMDelay Switch BridgeERROR(Use `node --trace-deprecation ...` to show where the warning was created)

**Comment by nitaybz** [comment]
should be fixed
