### ISSUE TITLE
[Feature Request] Cycle Sensor

### ISSUE THREAD

**Issue by jvacek** [nitaybz/homebridge-delay-switch#58]
So I've got the following use-case: I have a mosquito repellent in a smart plug running from sunset to sunrise -2hrs. I would like it to not be on the whole night and keep turning on and off every 30 mins in this case.

What I've currently got is 3 switches. Two that have 30 minute timers (each switches the other one on when they toggle off), and one "stateful" dummy switch which acts as the "master switch" (kickstart the "cycle" by turning on A, and switches off both when it's turned off). The plug turns on and off based on timer A. This is all automated within the Home app and takes about 6 automations.

Instead of this slightly hacky setup, I would propose the following:
A "Cycle" switch that would have a dedicated occupancy sensor; when the switch is on, the occupancy sensor would stay on for `n` seconds, and then turn off for `n` seconds, looping until the switch is turned off.

This way I could simply automate the plug based on the state of the sensor.

Curious whether you'd think this would fit this plugin :)

**Comment by nitaybz** [comment]
unfortunately this is out of the scope of this plugin, I'm trying to keep things simple.
