### ISSUE TITLE
Occupancy Sensor Not Triggering

### ISSUE THREAD

**Issue by Josh-Duncan** [nitaybz/homebridge-delay-switch#59]
I am currently running into an issue where the Occupancy sensor is not being triggered when the switch is flipped to on.

The log registers the change, and the switch toggles.

Example config:
```
            "name": "Office Occupancy",
            "delay": 900000,
            "sensorType": "occupancy",
            "flipSensorState": false,
            "startOnReboot": false,
            "accessory": "DelaySwitch"
```

homebridge-delay-switch v3.0.3
homebridge-config-ui-x v4.45.0
x2 AppleTV's and x1 HomePod Mini's configured as available hubs running 15.5

![image](https://user-images.githubusercontent.com/53050067/169896843-a6ac668e-67b7-45a8-95c0-4282f2d26537.png)

**Comment by nitaybz** [comment]
Occupancy is triggered when switch is turned off on it's own when timer is over
