### ISSUE TITLE
Request: Trigger when switch start ON

### ISSUE THREAD

**Issue by Geoff-Hz** [nitaybz/homebridge-delay-switch#60]
Hi,
Is it possible to have the option that when the switch start ON make a trigger?
I would like to have this to know with notification when switch start.
Btw, I use most the time your switch to have a notification of the automatisation's status 
Maybe you have a trick to do that.
Thanks

**Comment by nitaybz** [comment]
you can just create another delay switch with very little timer and set automation to turn on this switch when the other switch is ON
