### ISSUE TITLE
Feature request: no sensor reset after timer completion

### ISSUE THREAD

**Issue by mscottco** [nitaybz/homebridge-delay-switch#62]
Would it be possible to add a reset option so that the switch/sensor stays on when the timer is up?

I'm currently using this plugin to turn off the HVAC if someone leaves a door open for an extended period of time. If a door/window opens or closes, it will throw the switch and start the timer. Ideally I'd like to leave the switch and sensor activated at the end of the timer so its not possible to turn the HVAC back on even if the doors are open.

Hope that makes sense, happy to answer any queries! Cheers!

**Comment by nitaybz** [comment]
unfortunately that's kind of destroy the simplicity of this plugin.
I would just use a "dummy switch" with this plugin or have an automation to turn the HVAC off if it was turned on and window is open
