### ISSUE TITLE
[Feature Request] Add “leak” sensorType for a bolder alert option 🚨 

### ISSUE THREAD

**Issue by mattsign** [nitaybz/homebridge-delay-switch#64]
Howdy friend — love your plugin! Any chance adding a “leak” sensorType might happen down the road? 

I’m interested in that particular sensor type since the leak sensor alerts that HomeKit sends are a lot more interruptive and sound audible alerts on all my devices and HomePods (without stopping any music that might be playing). 

My setup: I’m using a contact sensor attached to a fridge door paired with your Homebridge delay switch plugin to trigger an alert after 90s to encourage my household to go shut the door, but would love the priority audible alert of a leak!

**Comment by seanhealy** [comment]
Would also love this.

**Comment by nitaybz** [comment]
available in plugin version 3.1.1
