### ISSUE TITLE
Help please

### ISSUE THREAD

**Issue by richardtjscholtz** [nitaybz/homebridge-delay-switch#69]
Ive been trying now for days myself to create a similar plugin like this, but instead of the sensors being turned on, I want a critical alert notification to pop up. Almost like a "break is over" alarm. Can aaaayone pleeeease help me

**Comment by AussieFries** [comment]
AFAIK the homebridge-contact-left-open plugin is the only one that can do this

**Comment by nitaybz** [comment]
it's possible now in the new version v3.1.0
you can choose leak detector to have a critical notification
