### ISSUE TITLE
Proposed Update to Reset Timer if Switch Turned on While Already On

### ISSUE THREAD

**Issue by tehoro** [nitaybz/homebridge-delay-switch#7]
A very good use case for this timer would be to turn lights on in a hallway when motion is detected, and keep them on for (say) 5 minutes after the last motion is seen.

However, as written, the switch will stay on for delayTime milliseconds after it is first switched on.  Switching it on again, while it is already on, does not reset the timer.

I propose adding this line of code just after line 30 of index.js 

    clearTimeout(this.Timer);    // clear any previous timer

so the new code in that area would read:

    if (on) {
       clearTimeout(this.Timer);    // clear any previous timer
       this.Timer = setTimeout(function() {
 
I have tested this and found it to work.

This could be an update to the current plugin.  However, if it is seen as too significant a change to the existing behaviour, a new plugin based on the current one could be provided.

Happy to get feedback on this.

**Comment by nitaybz** [comment]
That is actually a great idea, I just did your fix...

**Comment by tehoro** [comment]
Thanks!
