### ISSUE TITLE
Option to stop timer

### ISSUE THREAD

**Issue by AussieFries** [nitaybz/homebridge-delay-switch#70]
Thank you for your work on the Delay Switch. It's great!

I use your plugin to turn off the air purifier when the backdoor is opened for more than 30 seconds. In the summer we leave the backdoor open and I don't want the air purifier to clean the outside air.

So when the backdoor is opened for less than 30 sec the air purifier doesn't have to be switched off. However once the door has been opened the Delay Switch timer starts counting. Is there any way to stop the timer?

**Comment by nitaybz** [comment]
yes, you can just turn off the switch and timer will be stopped
