### ISSUE TITLE
Can you help me?

### ISSUE THREAD

**Issue by kalety** [nitaybz/homebridge-delay-switch#9]
Hello, I don´t get it work... I wish: movement sensor detects->switch on lights-> switch delay (several seconds)-> switch off lights... . I tried several ways but.... nothing... Can you help me with a clearer example?

Thanks in advance!!!

**Comment by nitaybz** [comment]
You need these automations:
 **IF** movement sensor detects **THEN** Turn ON delay switch
 **IF** delay switch Turns ON **THEN** Turn ON Lights
 **IF** delay switch Turns OFF **THEN** Turn OFF Lights

**Comment by kalety** [comment]
Thank you very much for your quickly response!!!. I will try it and tell you...

**Comment by kalety** [comment]
Perfect!, thanks! :))

**Comment by kalety** [comment]
Perfect!, thanks! :))

**Comment by kalety** [comment]
Closing....
